[PHP]
; 错误处理
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
display_startup_errors = Off
log_errors = On

; 禁用内存使用信息的收集
mysqlnd.collect_memory_statistics = Off

; 关闭 PHP 信息输出（安全）
expose_php = Off

; 文件上传设置
; 壁纸原图可能非常大，建议将限制提高到 50M 以防 4K/8K 超高清图片上传失败
max_file_uploads = 10
post_max_size = 50M
upload_max_filesize = 50M

; 默认时区
date.timezone = Asia/Shanghai

; 最大超时时间
; 因为涉及大文件上传或临时流转，5秒可能导致上传失败，建议保守调整为 30 秒（图片裁剪我们放进异步队列）
max_execution_time = 30
max_input_time = 60

; 允许的最大内存
; 图像处理 (GD 库) 在内存中展开图片时极耗内存，512M 是非常稳妥的值
memory_limit = 512M

[opcache]
; 开启 Opcache
opcache.enable = 1
opcache.enable_cli = 1

; Opcache 占用的内存大小
opcache.memory_consumption = 256

; Interned String 使用的内存大小
opcache.interned_strings_buffer = 64

; 最大脚本数
opcache.max_accelerated_files = 100000

; 生产环境关闭文件变化检查，榨干最后一点 I/O 性能
; 注意：每次更新代码后必须重启 php 容器或重载 php-fpm
opcache.validate_timestamps = 0
opcache.revalidate_freq = 0
opcache.file_update_protection = 0

; Laravel 的路由和一些依赖可能需要读取注释 (Attributes/Annotations)
; Laravel 11 中大部分核心已不再依赖 DocBlock 注释，但某些扩展包可能还需要。保险起见设为 1，追求极致可设为 0。
opcache.save_comments = 1
